/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mimacom.manager.tasklist.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.mimacom.manager.tasklist.model.TaskStatus;
import com.mimacom.manager.tasklist.model.TaskStatusModel;
import com.mimacom.manager.tasklist.model.TaskStatusSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TaskStatus service. Represents a row in the &quot;tlm_TaskStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TaskStatusModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskStatusImpl
 * @generated
 */
@JSON(strict = true)
public class TaskStatusModelImpl
	extends BaseModelImpl<TaskStatus> implements TaskStatusModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task status model instance should use the <code>TaskStatus</code> interface instead.
	 */
	public static final String TABLE_NAME = "tlm_TaskStatus";

	public static final Object[][] TABLE_COLUMNS = {
		{"taskStatusId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"type_", Types.INTEGER},
		{"progress", Types.INTEGER}, {"taskId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("taskStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("progress", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("taskId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table tlm_TaskStatus (taskStatusId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,type_ INTEGER,progress INTEGER,taskId LONG)";

	public static final String TABLE_SQL_DROP = "drop table tlm_TaskStatus";

	public static final String ORDER_BY_JPQL =
		" ORDER BY taskStatus.taskStatusId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY tlm_TaskStatus.taskStatusId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long PROGRESS_COLUMN_BITMASK = 1L;

	public static final long TASKID_COLUMN_BITMASK = 2L;

	public static final long TYPE_COLUMN_BITMASK = 4L;

	public static final long USERID_COLUMN_BITMASK = 8L;

	public static final long TASKSTATUSID_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TaskStatus toModel(TaskStatusSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TaskStatus model = new TaskStatusImpl();

		model.setTaskStatusId(soapModel.getTaskStatusId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setType(soapModel.getType());
		model.setProgress(soapModel.getProgress());
		model.setTaskId(soapModel.getTaskId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TaskStatus> toModels(TaskStatusSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TaskStatus> models = new ArrayList<TaskStatus>(soapModels.length);

		for (TaskStatusSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TaskStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taskStatusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaskStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taskStatusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaskStatus.class;
	}

	@Override
	public String getModelClassName() {
		return TaskStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TaskStatus, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TaskStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskStatus, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TaskStatus)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TaskStatus, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TaskStatus, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TaskStatus)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TaskStatus, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TaskStatus, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TaskStatus>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TaskStatus.class.getClassLoader(), TaskStatus.class,
			ModelWrapper.class);

		try {
			Constructor<TaskStatus> constructor =
				(Constructor<TaskStatus>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TaskStatus, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TaskStatus, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TaskStatus, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TaskStatus, Object>>();
		Map<String, BiConsumer<TaskStatus, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TaskStatus, ?>>();

		attributeGetterFunctions.put(
			"taskStatusId", TaskStatus::getTaskStatusId);
		attributeSetterBiConsumers.put(
			"taskStatusId",
			(BiConsumer<TaskStatus, Long>)TaskStatus::setTaskStatusId);
		attributeGetterFunctions.put("groupId", TaskStatus::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<TaskStatus, Long>)TaskStatus::setGroupId);
		attributeGetterFunctions.put("companyId", TaskStatus::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TaskStatus, Long>)TaskStatus::setCompanyId);
		attributeGetterFunctions.put("userId", TaskStatus::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TaskStatus, Long>)TaskStatus::setUserId);
		attributeGetterFunctions.put("userName", TaskStatus::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TaskStatus, String>)TaskStatus::setUserName);
		attributeGetterFunctions.put("createDate", TaskStatus::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TaskStatus, Date>)TaskStatus::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TaskStatus::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TaskStatus, Date>)TaskStatus::setModifiedDate);
		attributeGetterFunctions.put("type", TaskStatus::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<TaskStatus, Integer>)TaskStatus::setType);
		attributeGetterFunctions.put("progress", TaskStatus::getProgress);
		attributeSetterBiConsumers.put(
			"progress",
			(BiConsumer<TaskStatus, Integer>)TaskStatus::setProgress);
		attributeGetterFunctions.put("taskId", TaskStatus::getTaskId);
		attributeSetterBiConsumers.put(
			"taskId", (BiConsumer<TaskStatus, Long>)TaskStatus::setTaskId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTaskStatusId() {
		return _taskStatusId;
	}

	@Override
	public void setTaskStatusId(long taskStatusId) {
		_taskStatusId = taskStatusId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	@JSON
	@Override
	public int getProgress() {
		return _progress;
	}

	@Override
	public void setProgress(int progress) {
		_columnBitmask |= PROGRESS_COLUMN_BITMASK;

		if (!_setOriginalProgress) {
			_setOriginalProgress = true;

			_originalProgress = _progress;
		}

		_progress = progress;
	}

	public int getOriginalProgress() {
		return _originalProgress;
	}

	@JSON
	@Override
	public long getTaskId() {
		return _taskId;
	}

	@Override
	public void setTaskId(long taskId) {
		_columnBitmask |= TASKID_COLUMN_BITMASK;

		if (!_setOriginalTaskId) {
			_setOriginalTaskId = true;

			_originalTaskId = _taskId;
		}

		_taskId = taskId;
	}

	public long getOriginalTaskId() {
		return _originalTaskId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TaskStatus.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaskStatus toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TaskStatus>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaskStatusImpl taskStatusImpl = new TaskStatusImpl();

		taskStatusImpl.setTaskStatusId(getTaskStatusId());
		taskStatusImpl.setGroupId(getGroupId());
		taskStatusImpl.setCompanyId(getCompanyId());
		taskStatusImpl.setUserId(getUserId());
		taskStatusImpl.setUserName(getUserName());
		taskStatusImpl.setCreateDate(getCreateDate());
		taskStatusImpl.setModifiedDate(getModifiedDate());
		taskStatusImpl.setType(getType());
		taskStatusImpl.setProgress(getProgress());
		taskStatusImpl.setTaskId(getTaskId());

		taskStatusImpl.resetOriginalValues();

		return taskStatusImpl;
	}

	@Override
	public int compareTo(TaskStatus taskStatus) {
		long primaryKey = taskStatus.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TaskStatus)) {
			return false;
		}

		TaskStatus taskStatus = (TaskStatus)object;

		long primaryKey = taskStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TaskStatusModelImpl taskStatusModelImpl = this;

		taskStatusModelImpl._originalUserId = taskStatusModelImpl._userId;

		taskStatusModelImpl._setOriginalUserId = false;

		taskStatusModelImpl._setModifiedDate = false;

		taskStatusModelImpl._originalType = taskStatusModelImpl._type;

		taskStatusModelImpl._setOriginalType = false;

		taskStatusModelImpl._originalProgress = taskStatusModelImpl._progress;

		taskStatusModelImpl._setOriginalProgress = false;

		taskStatusModelImpl._originalTaskId = taskStatusModelImpl._taskId;

		taskStatusModelImpl._setOriginalTaskId = false;

		taskStatusModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaskStatus> toCacheModel() {
		TaskStatusCacheModel taskStatusCacheModel = new TaskStatusCacheModel();

		taskStatusCacheModel.taskStatusId = getTaskStatusId();

		taskStatusCacheModel.groupId = getGroupId();

		taskStatusCacheModel.companyId = getCompanyId();

		taskStatusCacheModel.userId = getUserId();

		taskStatusCacheModel.userName = getUserName();

		String userName = taskStatusCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			taskStatusCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			taskStatusCacheModel.createDate = createDate.getTime();
		}
		else {
			taskStatusCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taskStatusCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taskStatusCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		taskStatusCacheModel.type = getType();

		taskStatusCacheModel.progress = getProgress();

		taskStatusCacheModel.taskId = getTaskId();

		return taskStatusCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TaskStatus, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TaskStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TaskStatus)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TaskStatus, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TaskStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TaskStatus)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TaskStatus>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _taskStatusId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private int _progress;
	private int _originalProgress;
	private boolean _setOriginalProgress;
	private long _taskId;
	private long _originalTaskId;
	private boolean _setOriginalTaskId;
	private long _columnBitmask;
	private TaskStatus _escapedModel;

}